webtalk_init -webtalk_dir C:/Users/ads5915/Desktop/FinalProject/FinalProject.sim/sim_1/behav/xsim/xsim.dir/test_bench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Dec 21 15:23:05 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210019088_174110206_210672584_548" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "64c0badf-6bae-40ae-bf5c-2c5d84b604b1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c72d1a3d0fdf45babfeea45bed927994" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "78" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3408 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6088_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2507534173 -regid "210019088_174110206_210672584_548" -xml C:/Users/ads5915/Desktop/FinalProject/FinalProject.sim/sim_1/behav/xsim/xsim.dir/test_bench_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ads5915/Desktop/FinalProject/FinalProject.sim/sim_1/behav/xsim/xsim.dir/test_bench_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ads5915/Desktop/FinalProject/FinalProject.sim/sim_1/behav/xsim/xsim.dir/test_bench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
